server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL:jdbc:postgresql://dev-db:5432/fitflow_dev}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
logging.level.com.training.fitflow=DEBUG

management.endpoints.web.exposure.include=health,info,metrics,prometheus,beans,env,mappings,configprops

jwt.secret=fitflow-dev-secret-key-32-chars-min
jwt.expiration=43200000