server.port=8080

database.url=${DB_URL}
database.username=${DB_USERNAME}
database.password=${DB_PASSWORD}

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true