server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/fitflow_local
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
logging.level.com.training.fitflow=DEBUG