package com.training.fitflow.dto.trainer.response;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Response after trainer creation")
public record TrainerCreateResponse(
        @Schema(example = "john.trainer")
        String username,
        @Schema(example = "autoGeneratedPass123")
        String password
) {}