package com.training.fitflow.dto.trainee.response;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Response after trainee creation")
public record TraineeCreateResponse(
        @Schema(example = "john.doe")
        String username,
        @Schema(example = "autoGeneratedPass123")
        String password
) {}
